Repository IntersectMBO/lsm-tree, pull requests merged in 2024-09, with the labels that each got.

#364 Correct `entriesCount` to `entryCount`
  src/Database/LSMTree/Internal/IndexOrdinary.hs
Labels: bug

#393 Fix a bug in ordinary index search
  src/Database/LSMTree/Internal/IndexOrdinary.hs
Labels: bug

#363 Include the index type in the index versioning information
  doc/format-run.md
  src/Database/LSMTree/Internal/IndexCompact.hs
  src/Database/LSMTree/Internal/IndexOrdinary.hs
Labels: enhancement

#400 update security.md
  SECURITY.md
Labels: documentation

#406 Add `Arbitrary` instantiation for primitive vectors
  src-extras/Database/LSMTree/Extras/Generators.hs
  test/Test/Database/LSMTree/Internal/Chunk.hs
Labels: enhancement
